# Generated by Django 3.1.7 on 2021-04-04 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=100, verbose_name='цена'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_app_1.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cotegory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_app_1.cotegory'),
        ),
    ]
